PolaHotel/Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolaHotel.Models
{
   
    public class Room
    {
        //[Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        //[Remote(action: "CheckRoomNumber", controller: "Room", ErrorMessage = "Room Already Exist")]

        public int ID { get; set; }

        public string Image { get; set; }

        public string Description { get; set; }
        
        [Required]
        [Display(Name = "You should select room's availability?")]
        public bool isavailble { get; set; }

        //[Required(ErrorMessage = "enter number of Beeds")]
        //[Range(1, 4, ErrorMessage = "Number Of Beds Must Be Less Than 5 Beds")]
        //public int NumberOfBeeds { get; set; }  

        [ForeignKey("RoomCategory")]
        public int catID { set; get; }

        [ForeignKey("catID")]

        public virtual Room_Category RoomCategory { get; set; }

        //[ForeignKey("Reservation")]
        //public int ReservID { set; get; }

        //[ForeignKey("ReservID")]
        //public virtual Reservation Reservation { get; set; }
        

       public virtual ICollection<RoomReservation> RoomReservations { get; set; }

        


    }
}

PolaHotel/Controllers/RoomController.cs
using PolaHotel.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolaHotel.Controllers
{
    public class RoomController : Controller
    {
        // GET: Room
        //RoomService service = new RoomService();
        ApplicationDbContext Context = new ApplicationDbContext();


        [Authorize]
        public ActionResult Index()
        {
            ViewBag.Reserve = Context.roomReservations.ToList();

            return View(Context.Room_Categories.ToList());
        }

        public ActionResult IndexCustomer()
        {
            ViewBag.Reserve = Context.roomReservations.ToList();

            return View(Context.Room_Categories.ToList());
        }

        [Authorize]

        public ActionResult Add()
        {
            ViewBag.RoomCategorys = Context.Room_Categories.ToList();
            return View();
        }


        [HttpPost]
        public ActionResult Add(Room room, HttpPostedFileBase upload)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.RoomCtegorys = Context.Room_Categories.ToList();
                return View(room);
            }
            else
            {
                try
                {
                    if (upload != null)
                    {
                        string path = Path.Combine(Server.MapPath("~/Content/Images"), upload.FileName);
                        upload.SaveAs(path);
                        room.Image = upload.FileName;
                    }
                    Context.Rooms.Add(room);


                    Context.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    ViewBag.RoomCtegorys = Context.Room_Categories.ToList();
                    return View(room);
                }

            }

        }


        [Authorize]

        public ActionResult Edit(int roomNo)
        {
            ViewBag.RoomCtegorys = Context.Room_Categories.ToList();
            return View(Context.Rooms.FirstOrDefault(r => r.ID == roomNo));

        }


        [HttpPost]
        public ActionResult Edit(Room room, HttpPostedFileBase upload)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.RoomCtegorys = Context.Room_Categories.ToList();
                return View(room);
            }
            else
            {
                try
                {
                    if (upload != null)
                    {
                        string path = Path.Combine(Server.MapPath("~/Content/Images"), upload.FileName);
                        upload.SaveAs(path);
                        room.Image = upload.FileName;
                    }
                    Room Room = Context.Rooms.FirstOrDefault(r => r.ID == room.ID);
                    if (Room != null)
                    {
                       
                        Room.Image = room.Image;
                        Room.Description = room.Description;
                        Room.isavailble = room.isavailble;
                        //Room.NumberOfBeeds = room.NumberOfBeeds;
                        Room.catID = room.catID;
                    }
                    Context.SaveChanges();


                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    ViewBag.RoomCtegorys = Context.Room_Categories.ToList();
                    return View(room);
                }

            }

        }

        [Authorize]


        public ActionResult Details(int id)
        {
            Room room = Context.Rooms.FirstOrDefault(r => r.ID == id);
            return View(room);
        }

        public ActionResult Delete(int id)
        {
            Room room = Context.Rooms.FirstOrDefault(r => r.ID == id);
            Context.Rooms.Remove(room);
            Context.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult CheckRoomNumber(int Room_Number)
        {
            Room room = Context.Rooms.FirstOrDefault(r => r.ID == Room_Number);
            if (room != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(true, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetRoomForCategory(int id)
        {

            List<Room> rooms = Context.Rooms.Where(r => r.catID == id).ToList();

            return View(rooms);
        }
    }
}

PolaHotel/Views/Room/Add.cshtml
@model PolaHotel.Models.Room

@{
    ViewBag.Title = "AddStudent";
    Layout = "~/Views/Shared/_Layout.cshtml";
    SelectList RoomCategory = new SelectList(ViewBag.RoomCategorys, "catID", "View");
}

<style>
    body {
        background: #808080
    }
    .form {
      
        background: white;
        margin: auto auto;
        padding: 20px;
        border-radius: 10px;
        width:100%
    }
    .control-label {
        font-weight: bold;
        color: #808080;
    }
</style>

<div class="container">
    @using (Html.BeginForm("Add", "Room", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form" }))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Room</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.Label("Number Of Room", htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.NumberofRoom, new { htmlAttributes = new { @class = "form-control", @style = "background: #f1f3f4;", @placeholder = "Enter Number Of Beds" } })
                        @Html.ValidationMessageFor(model => model.NumberofRoom, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label " })
                    <div class="col-md-12">
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @style = "background: #f1f3f4;", @placeholder = "Enter Room Description" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">

                <div class="form-group">
                    @Html.Label("Price", "Price", htmlAttributes: new { @class = "control-label " })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @style = "background: #f1f3f4;", @placeholder = "Enter Room Price" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    @Html.Label("Check If The Room Is Available Or Not ", htmlAttributes: new { @class = "control-label " })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.isavailble, new { htmlAttributes = new { @checked = "checked" } })
                        <span>Is Available</span>
                        @Html.ValidationMessageFor(model => model.isavailble, "", new { @class = "text-danger" })

                    </div>
                </div>
            </div>
        </div>

            <div class="row">
                <div class="col-md-6">
                    @*<div class="form-group">
                        @Html.Label("Number Of Beeds", htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-12">
                            @Html.EnumDropDownListFor(model => model.Numbed, new { htmlAttributes = new { @class = "form-control", @style = "background: #f1f3f4;", @placeholder = "Enter Number Of Beds" } })
                            @Html.ValidationMessageFor(model => model.Numbed, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Choose Room Category", htmlAttributes: new { @class = "control-label " })
                        <div class="col-md-12">
                            @Html.DropDownList("catID", RoomCategory , htmlAttributes: new { @class = "form-control", @style = "background: #f1f3f4;" })
                            @Html.ValidationMessageFor(model => model.catID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <br />
            @*<div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-12">
                <input type="file" name="upload" class="form-control" style="border:hidden;background: #f1f3f4;" />

            </div>
        </div>*@
            <div class="row">
                <div class="col-md-12">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" name="upload" id="customFile">
                        <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>
                    <br><br />
                        <div class="row" style="float:right">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-success"})

                                    </div>

                                </div>
                            </div>
                            <div class="col-md-6">

                                <div class="form-group">
                                    <div class="col-md-12">
                                        <input type="submit" value="Save" class="btn btn-primary" />

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        }


    </div>

<br />
@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $(".form-control").click(function () {
                $(".form-control").css("background","white");
            });
            $(".form-control").mouseleave(function () {
                $(".form-control").css("background", "#f1f3f4");
            });
        })
    </script>
    
}

PolaHotel/Views/Room/Details.cshtml
@model PolaHotel.Models.Room

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    span{ font-size:16px;font-weight:bold}
</style>

<h4>Room Details</h4>
<hr />
<div class="card" style="width:400px;margin:auto auto;background:#dee1e6" >
    <img class="card-img-top" src="~/Content/Images/@Model.Image" alt="Card image" style="height:200px;">
    <div class="card-body">
        @*<h4 class="card-title text-center">Room (@Model.Room_Number)</h4>*@
        <br />
        <hr />
        <span>Type :</span> <i> @Model.RoomCategory.View</i>

        <p class="card-text"><span>Description :</span><i> @Model.Description</i></p>
        <p><span>Price :</span> <i>@Model.Price Pound</i></p>
        @*<p><span>Beds :</span> <i>@Model.NumberOfBeeds</i></p>*@

        <span>Avialability :</span> @Html.DisplayFor(model => model.isavailble)
        <br />        <br />

        <a href="/Room/Index" class="btn btn-primary" style="margin-left:40%">Go Back</a>
    </div>
</div>
<br/><br/>

PolaHotel/Views/Room/Edit.cshtml
@model PolaHotel.Models.Room

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    SelectList RoomCategory = new SelectList(ViewBag.RoomCtegorys, "catID", "Category_Name");
}

    <style>
        body {
            background: #808080
        }

        .form {
            background: white;
            margin: auto auto;
            padding: 20px;
            border-radius: 10px;
            width: 100%
        }

        .control-label {
            font-weight: bold;
            color: #808080;
        }
    </style>
    <div class="container">

        @using (Html.BeginForm("Edit", "Room", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form" }))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Edit Room</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @style = "background: #f1f3f4;" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Price", "Price", htmlAttributes: new { @class = "control-label " })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @style = "background: #f1f3f4;" } })
                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Check If The Room Is Available Or Not ", htmlAttributes: new { @class = "control-label " })
                        <div class="col-md-12">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.isavailble)
                                @Html.ValidationMessageFor(model => model.isavailble, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    @*<div class="form-group">
                        @Html.Label("Number Of Beeds", htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.NumberOfBeeds, new { htmlAttributes = new { @class = "form-control", @style = "background: #f1f3f4;" } })
                            @Html.ValidationMessageFor(model => model.NumberOfBeeds, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Choose Room Category", htmlAttributes: new { @class = "control-label " })
                        <div class="col-md-12">
                            @Html.DropDownList("Room_Categ_ID", RoomCategory, htmlAttributes: new { @class = "form-control", @style = "background: #f1f3f4;" })
                            @Html.ValidationMessageFor(model => model.catID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
               <label class="control-label">Image</label>
                    <div class="col-md-12">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" name="upload" id="customFile">
                            <label class="custom-file-label" for="customFile">Choose file</label>
                        </div>
                    </div>

                    <br>
                    <div class="row" style="float:right">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-12">
                                    @Html.ActionLink("Room List", "Index", null, new { @class = "btn btn-success", @style = "width: 123%;" })

                                </div>

                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="submit" value="Update" class="btn btn-primary" />

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        }

        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

PolaHotel/Views/Room/GetRoomForCategory.cshtml
@model IEnumerable<PolaHotel.Models.Room>



@{
    ViewBag.Title = "GetRoomForCategory";
    Layout = "~/Views/Shared/_Test.cshtml";

}
<div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-inner position-relative">
            <div class="preloader-circle"></div>
            <div class="preloader-img pere-text">
                <strong>Hotel</strong>
            </div>
        </div>
    </div>
</div>
<!-- Preloader Start -->
<!-- slider Area Start-->
<div class="slider-area">
    <div class="single-slider hero-overly slider-height2 d-flex align-items-center" style=" background-image: url('/Content/Images/Room.jpg');">
        <div class="container">
            <div class="row ">
                <div class="col-md-11 offset-xl-1 offset-lg-1 offset-md-1">
                    <div class="hero-caption">
                        <span>Room</span>
                        <h2>Room</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container" style="margin-top:50px">
    <div class="row">
        @foreach (var item in Model)
        {


            <div class="card col-lg-4" style="width:400px">
                <img class="card-img-top" src="~/Content/Images/@item.Image" alt="Card image" style="width:100%;height: 200px;">
                <div class="card-body">
                    <h4 class="card-title"><b>@item.Description</b></h4>



                </div>

            </div>


        }
    </div>
</div>

PolaHotel/Views/Room/Index.cshtml
@model IEnumerable<PolaHotel.Models.Room_Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<PolaHotel.Models.RoomReservation> rooms = ViewBag.Reserve;


}


<h4>All Rooms</h4>
<hr />




<table class="table table-hover">
    <thead class="bg-dark" style="color:white">
        <tr>

            <th>
                Room Type
            </th>
            <th>
                Image
            </th>
            <th>
                Price
            </th>
            <th>
                Number of Rooms
            </th>

            <th>
                Available Room
            </th>



        </tr>
    </thead>


    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.View)
    </td>


    <td>
        <img src="~/Content/Images/@item.Image" style="width:150px;height:90px;" />
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Price)
    </td>
    <td>
        @{
            int x = item.Rooms.Count();

        }
        <p>@x</p>
    </td>
    <td>
        @{
            var result = item.Rooms.Where(r => !rooms.Any(r2 => r2.RoomID == r.ID)).Count();
        }
        <p>@result</p>

    </td>

    @*<td>
            @Html.DisplayFor(modelItem => item.Numbed)
        </td>*@

    @*<td>
            @Html.ActionLink("Edit", "Edit", new { roomNo = item.ID }, new { @class = "btn btn-info", @style = "width:70px" }) |
            @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-primary", @style = "width:70px" }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger", @style = "width:70px" })
        </td>*@
</tr>
    }

</table>




@*<div class="d-flex" style="word-wrap:break-word;background:red;width:100%" >
    @foreach (var item in Model)
    {
    <div class="card" style="width:50%;margin:auto auto">
        <img class="card-img-top" src="~/Content/Images/@item.Image" alt="Card image" style="height:200px;">
        <div class="card-body">
            <h4 class="card-title text-center">Room (@item.Room_Number)</h4>
            <hr />
            <span>Type :</span> <i> @item.Room_Category.Category_Name</i>

            <p class="card-text"><span>Description :</span> @item.Description</p>
            <p><span>Price :</span> @item.Price Pound</p>
            <p><span>Beds :</span> @item.NumberOfBeeds</p>
            <div>
                <span> Services :</span>
                @foreach (var t in item.RoomServices)
                {
                    <input type="checkbox" checked disabled />
                    @Html.DisplayFor(modelItem => t.Services.Name)
                }
            </div>
            <span>Avialability :</span> @Html.DisplayFor(model => item.isavailble)
            <br />
            <a href="/Room/Index" class="btn btn-primary" style="margin-left:40%">Go Back</a>
        </div>
    </div>
    }
    </div>
*@

PolaHotel/Views/Room/IndexCustomer.cshtml
@model IEnumerable<PolaHotel.Models.Room_Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Test.cshtml";
    List<PolaHotel.Models.RoomReservation> rooms = ViewBag.Reserve;


}







<table class="table table-hover">
    <thead class="bg-dark" style="color:white">
        <tr>

            <th>
                Room Type
            </th>
            <th>
                Image
            </th>
            <th>
                Price
            </th>





        </tr>
    </thead>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.View)
            </td>


            <td>
                <img src="~/Content/Images/@item.Image" style="width:150px;height:90px;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>




        </tr>
    }

</table>



<div class="container-fluid" >
    <div class="row">
        <div class="col-sm-4">
            <img src="~/Content/Images/image.jpg" alt="img1" style="width:100%;height:250px" />
        </div>
        <div class="col-sm-4">
            <img src="~/Content/Images/image2.jpg" alt="img1" style="width:100%;height:250px" />
        </div>
        <div class="col-sm-4">
            <img src="~/Content/Images/image4.jpg" alt="img1" style="width:100%;height:250px" />
        </div>
    </div>
</div>