PolaHotel/Models/Room_Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PolaHotel.Models
{
    
    public class Room_Category
    {
       
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int catID { get; set; }

        [Required]
        [Display(Name = "Entert Room Price ?")]
        public double Price { get; set; }
        public string Image { get; set; }

        public string View { set; get; }

       
        public virtual ICollection<Room> Rooms { get; set; }


       


    }
}

PolaHotel/Controllers/Room_CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PolaHotel.Models;

namespace PolaHotel.Controllers
{
    public class Room_CategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]

        // GET: Room_Category
        public ActionResult Index()
        {
            return View(db.Room_Categories.ToList());
        }
        [Authorize]

        // GET: Room_Category/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room_Category room_Category = db.Room_Categories.Find(id);
            if (room_Category == null)
            {
                return HttpNotFound();
            }
            return View(room_Category);
        }
        [Authorize]

        // GET: Room_Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Room_Category/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Room_Category room_Category, HttpPostedFileBase upload)
        {
            //if (ModelState.IsValid)
            //{
            //    db.Room_Categories.Add(room_Category);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            if (!ModelState.IsValid)
            {
                return View(room_Category);
            }
            else
            {
                try
                {
                    if (upload != null)
                    {
                        string path = Path.Combine(Server.MapPath("~/Content/Images"), upload.FileName);
                        upload.SaveAs(path);
                        room_Category.Image = upload.FileName;
                    }
                    db.Room_Categories.Add(room_Category);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(room_Category);
                }

            }
        }
        [Authorize]

        // GET: Room_Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room_Category room_Category = db.Room_Categories.Find(id);
            if (room_Category == null)
            {
                return HttpNotFound();
            }
            return View(room_Category);
        }

        // POST: Room_Category/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Room_Category room_Category, HttpPostedFileBase upload)
        {
            //if (ModelState.IsValid)
            //{
            //    db.Entry(room_Category).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            if (!ModelState.IsValid)
            {
                return View(room_Category);
            }
            else
            {
                try
                {
                    if (upload != null)
                    {
                        string path = Path.Combine(Server.MapPath("~/Content/Images"), upload.FileName);
                        upload.SaveAs(path);
                        room_Category.Image = upload.FileName;
                    }
                    Room_Category Room = db.Room_Categories.FirstOrDefault(r => r.catID == room_Category.catID);
                    if (Room != null)
                    {
                        Room.View = room_Category.View;
                        Room.Image = room_Category.Image;
                       
                    }
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(room_Category);
                }

            }
        }

        // GET: Room_Category/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Room_Category room_Category = db.Room_Categories.Find(id);
        //    if (room_Category == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(room_Category);
        //}

        //// POST: Room_Category/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Room_Category room_Category = db.Room_Categories.Find(id);
        //    db.Room_Categories.Remove(room_Category);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        [Authorize]

        public ActionResult Delete(int id)
        {
            Room_Category room = db.Room_Categories.FirstOrDefault(r => r.catID == id);
            db.Room_Categories.Remove(room);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PolaHotel/Views/Room_Category/Create.cshtml
@model PolaHotel.Models.Room_Category

@{
    ViewBag.Title = "Create";
}
<style>
    body {
        background: #808080
    }

    .form {
        background: white;
        margin: auto auto;
        padding: 20px;
        border-radius: 10px;
        width: 100%
    }

    .control-label {
        font-weight: bold;
        color: #808080;
    }
</style>
<div class="container">

    @using (Html.BeginForm("Create", "Room_Category", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Room Category</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.View, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.View, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.View, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <label class="control-label">Add Image</label>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" name="upload" id="customFile">
                        <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>

                    <br><br />
                    <div class="row" style="float:right">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-12">
                                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-success" })

                                </div>

                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="submit" value="Save" class="btn btn-primary" />

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

PolaHotel/Views/Room_Category/Details.cshtml
@model PolaHotel.Models.Room_Category

@{
    ViewBag.Title = "Details";
}


    <h4>Details Room Category</h4>
    <hr />
<br/>
    @*<dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.catID }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

<div class="card" style="width:400px;margin:auto auto;background:#dee1e6">
    <img class="card-img-top" src="~/Content/Images/@Model.Image" alt="Card image" style="height:200px;">
    <div class="card-body">
        <h4 class="card-title text-center">Room (@Model.View)</h4>
        <br />       <br />

        <a href="/Room_Category/Index" class="btn btn-primary" style="margin-left:40%">Go Back</a>
    </div>
</div>
<br />
<br />

PolaHotel/Views/Room_Category/Edit.cshtml
@model PolaHotel.Models.Room_Category

@{
    ViewBag.Title = "Edit";
}

<style>
    body {
        background: #808080
    }

    .form {
        background: white;
        margin: auto auto;
        padding: 20px;
        border-radius: 10px;
        width: 100%
    }

    .control-label {
        font-weight: bold;
        color: #808080;
    }
</style>
<div class="container">

    @using (Html.BeginForm("Edit", "Room_Category", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Room Category</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.catID)
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.View, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.View, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.View, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="col-md-12">
                        <label class="control-label">Add Image</label>
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" name="upload" id="customFile">
                            <label class="custom-file-label" for="customFile">Choose file</label>
                        </div>
                        <br><br />
                        <div class="row" style="float:right">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-success" })

                                    </div>

                                </div>
                            </div>
                            <div class="col-md-6">

                                <div class="form-group">
                                    <div class="col-md-12">
                                        <input type="submit" value="Save" class="btn btn-primary" />

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PolaHotel/Views/Room_Category/Index.cshtml
@model IEnumerable<PolaHotel.Models.Room_Category>

@{
    ViewBag.Title = "Index";
}

<h4>All Room Categories</h4>
<hr />

<p>
    @Html.ActionLink("Create New", "Create",null,new { @class="btn btn-primary"})
</p>
<table class="table table-hover">
    <thead class="bg-dark" style="color:white">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.View)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.View)
            </td>
            <td>
                <img src="~/Content/Images/@item.Image" style="width:150px;height:90px;" />
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.catID }, new { @class = "btn btn-info", @style = "width:70px" }) |
                @Html.ActionLink("Details", "Details", new { id = item.catID }, new { @class = "btn btn-primary", @style = "width:70px;color:white" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.catID }, new { @class = "btn btn-danger", @style = "width:70px" })
            </td>
        </tr>
    }

</table>